# Generated by Django 6.0.1 on 2026-01-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='reaction',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
